spring:
  bot:
    plugin-list:
      # [BotPlugin]??[????&????]??
      - com.akiralumina.project.plugins.BotPlugin_Log # ????
      # [PrivatePlugin]??[????]??
      - com.akiralumina.project.plugins.PrivatePlugin_Greetings
      # [GroupPlugin]??[????]??
      - com.akiralumina.project.plugins.GroupPlugin_Greetings # 测试的问候插件
      - com.akiralumina.project.plugins.GroupPlugin_BanUser
      - com.akiralumina.project.plugins.GroupPlugin_BanUserDisable
      - com.akiralumina.project.plugins.GroupPlugin_UserBrand
      - com.akiralumina.project.plugins.GroupPlugin_UserPoke
      - com.akiralumina.project.plugins.GroupPlugin_UserSignIn

server:
  # lorca launcher use this port to connect bot , DO NOT CHANGE IT !
  port: 8081

logging:
  file:
    name: logs/luminabot-terminus.log


